apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kydg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kydg
    app.kubernetes.io/part-of: ci1t-43256-0094-app
  name: devfile-sample-kydg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kydg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kydg
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0094-tenant/ci1t-43256-0094-app/devfile-sample-kydg@sha256:c9a68adc39f2809d0a7cc0e1d1e08887f139a66f9150dd2f7ab41668d5b87e1d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
